[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dotfile-manager"
version = "0.0.1"
# dependencies = [
#     'importlib-metadata; python_version>"3.10"',
# ]

[project.scripts]
create_env = "main:main"